name: Periodic Dependency Update
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    types: [reopened]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_PAT }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - uses: thepwagner/action-update-go@main
        with:
          log_level: debug
          token: ${{ secrets.MY_GITHUB_PAT }}
      - uses: thepwagner/action-update-docker@main
        with:
          log_level: debug
          token: ${{ secrets.MY_GITHUB_PAT }}
          groups: |
            - name: golang
              pattern: golang
              post-script: script/sync-actions-go-version
